// Generated by CoffeeScript 1.7.1

/**
 * 
 * @author Kenneth van der Werf
 * @class moves
 * @package abstract/movement/moves
 * @description The base class from which actors are derived.
 * --
 * @param  {Class} createjs Framework for canvas game operations
 * @param  {Class} radio    Event emitter and receiver system
 * @return {Class}          Moves list
 */

(function() {
  define(['createjs', 'radio'], function(createjs, radio) {
    var Game;
    return Game = (function() {
      function Game() {}

      return Game;

    })();
  });

}).call(this);
