// Generated by CoffeeScript 1.7.1

/*
@Author: Kenneth van der Werf
@Name: Stage class
@Description: Stage that is handling all the actors
 */

(function() {
  define(['createjs'], function(createjs) {
    var Stage;
    return Stage = (function() {
      function Stage(strStageName) {
        this.strStageName = strStageName != null ? strStageName : 'myGameStage';
        this.objStage = new createjs.Stage(this.strStageName);
      }

      Stage.prototype.update = function() {
        return this.objStage.update();
      };

      return Stage;

    })();
  });

}).call(this);
