// Generated by CoffeeScript 1.6.3
define(["require", "jquery", "radio"], function(require, $, radio) {
  var EventDispatcher;
  return EventDispatcher = (function() {
    function EventDispatcher() {}

    EventDispatcher.prototype._eventDispatcher = $("body");

    EventDispatcher.prototype._dispatchEvent = function(strEventTarget, strEventName, objData, objThis) {
      if (objData == null) {
        objData = {};
      }
      if (objThis == null) {
        objThis = this;
      }
      this._eventDispatcher.trigger("" + strEventTarget + "." + strEventName, [objThis, objData]);
      return "Dispatched: " + strEventTarget + "." + strEventName;
    };

    EventDispatcher.prototype._bindEvent = function(strEventTarget, strEventName, funcTo) {
      this._eventDispatcher.on("" + strEventTarget + "." + strEventName, funcTo);
      return "Bound: " + strEventTarget + "." + strEventName;
    };

    return EventDispatcher;

  })();
});
