// Generated by CoffeeScript 1.6.3
define(["require", "jquery", "radio", "modules/abstract/inputcombinator"], function(require, $, radio, InputCombinator) {
  var Fighter;
  return Fighter = (function() {
    function Fighter() {
      this.strName = "Fighter";
      this.strDescription = "A fighter from the pits of hell.";
      this.strUID = (function() {
        var i, numString, numTotal, _i;
        numTotal = 10;
        numString = "";
        for (i = _i = 0; _i < numTotal; i = _i += 1) {
          numString = numString + Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
        }
        return numString;
      })();
      this.objDefaultProperties = {
        HEALTH: 100,
        STAMINA: 100,
        SPECIAL: 100,
        SPEED: 10
      };
      this.objProperties = $.extend({}, this.objDefaultProperties);
      this.objDefenses = {
        PHYSICAL: 0
      };
      this.strState = "IDLE";
      this.boolActive = true;
      this.objKeyBindings = {
        37: "LEFT",
        38: "UP",
        39: "RIGHT",
        40: "DOWN",
        65: "ACTION_ONE"
      };
      this.objKeyMapping = {
        "MOVE_RIGHT": ["RIGHT"],
        "MOVE_LEFT": ["LEFT"],
        "JUMP": ["UP"],
        "CROUCH": ["DOWN"]
      };
    }

    Fighter.prototype.setNewKey = function(strKey) {};

    Fighter.prototype.emitDamage = function(numAmount, strType) {
      if (strType == null) {
        strType = 'PHYSICAL';
      }
    };

    Fighter.prototype.emitState = function(strState, numDuration) {
      if (numDuration == null) {
        numDuration = 100;
      }
    };

    Fighter.prototype.onDamage = function(numAmount, strType) {};

    Fighter.prototype.onState = function(strState, numDuration) {};

    return Fighter;

  })();
});
