// Generated by CoffeeScript 1.6.3
define([], function() {
  var InputCombinator;
  return InputCombinator = (function() {
    function InputCombinator() {}

    InputCombinator.prototype.addKey = function(numKey) {};

    return InputCombinator;

  })();
});
