// Generated by CoffeeScript 1.6.3
define(["jquery", "radio", "mixer/mixerview", "mixer/mixermodel"], function($, radio, MixerView, MixerModel) {
  var Mixer;
  return Mixer = (function() {
    function Mixer() {}

    return Mixer;

  })();
});
