// Generated by CoffeeScript 1.7.1

/*
@Author: Kenneth van der Werf
@Name: Fighter class
@Description: Controller for fighter view and model
 */

(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['radio', 'keypress', 'modules/abstract/actors/actor', 'modules/abstract/movement/moves'], function(radio, keypress, Actor, Moves) {
    var Fighter;
    return Fighter = (function(_super) {
      __extends(Fighter, _super);

      function Fighter() {
        Fighter.__super__.constructor.call(this);
        this.strName = 'Fighter';
        this.strDescription = 'A fighter from the pits of hell.';
        this.loadSprites({
          'SPRITESHEET_JSON': './data/fighters/ryu.json',
          'SPRITESHEET_IMG': './data/fighters/ryu.png'
        });
        this.objMoves = new Moves({
          'left': 'left',
          'up': 'up',
          'right': 'right',
          'down': 'down',
          'action_one': 'a'
        });
      }

      Fighter.prototype.getMoves = function() {
        return this.objMoves;
      };

      Fighter.prototype.getInstance = function() {
        return this.objContainer;
      };

      return Fighter;

    })(Actor);
  });

}).call(this);
