// Generated by CoffeeScript 1.7.1
(function() {
  var config;

  config = {
    baseUrl: 'js',
    paths: {
      jquery: 'vendor/jquery',
      radio: 'vendor/radio',
      createjs: 'vendor/createjs',
      keypress: 'vendor/keypress'
    },
    shim: {
      createjs: {
        exports: 'createjs'
      },
      keypress: {
        exports: 'keypress'
      }
    }
  };

  require.config(config);

  requirejs(['modules/abstract/game/fightergame'], function(FighterGame) {
    return window.streetfighter = new FighterGame;
  });

}).call(this);
