// Generated by CoffeeScript 1.6.3
var config;

config = {
  baseUrl: "js",
  paths: {
    jquery: "vendor/jquery",
    radio: "vendor/radio"
  }
};

require.config(config);

requirejs(["jquery", "modules/abstract/fighter"], function($, Fighter) {
  window.f = new Fighter();
  return window.ff = new Fighter();
});
